### ISSUE TITLE
bug: Client crash in invite page when logged out

### ISSUE THREAD

**Issue by rhld16** [revoltchat/revite#737]
### What happened?

When attempting to open the invite page while logged out (on a self-hosted instance), a user is greeted with a Client Crash Report. Works normally when signed-in.

### Branch

Production (app.revolt.chat)

### Commit hash

95ebd93 (1.0.1)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'generateFileURL')
    at https://divolt.xyz/assets/main.10ca0d5d.js:17:554
    at https://divolt.xyz/assets/vendor.579a0f4a.js:6:52858
    at https://divolt.xyz/assets/vendor.579a0f4a.js:6:52049
    at v_ (https://divolt.xyz/assets/vendor.579a0f4a.js:6:13230)
    at t.track (https://divolt.xyz/assets/vendor.579a0f4a.js:6:18228)
    at D6 (https://divolt.xyz/assets/vendor.579a0f4a.js:6:52026)
    at un.a [as constructor] (https://divolt.xyz/assets/vendor.579a0f4a.js:6:52837)
    at un.w3 [as render] (https://divolt.xyz/assets/vendor.579a0f4a.js:1:8618)
    at np (https://divolt.xyz/assets/vendor.579a0f4a.js:1:6378)
    at X0 (https://divolt.xyz/assets/vendor.579a0f4a.js:1:2672)```
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
This commit is 24 days old, I'm going to close this as invalid.
(plus I think I fixed this)
