### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Aishima480** [revoltchat/revite#955]
### What happened?

Unable to join the voice channel in Revolt Desktop Client

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

782a9b5

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Relevant log output

```shell
Session.tsx:171 [FSM Anonymous] Object
Session.tsx:171 [FSM Anonymous] Object
xhr.js:210          POST https://app.revolt.chat/api/channels/01HK36HXV96X9YEH0AWN5PZSMZ/join_call 400
(anonymous) @ xhr.js:210
xhr @ xhr.js:15
dispatchRequest$1 @ dispatchRequest.js:58
Axios$2.request @ Axios.js:108
(anonymous) @ bind.js:9
req @ index.js:113
post @ index.js:138
(anonymous) @ Channels.js:503
(anonymous) @ Channels.js:13
__awaiter$b @ Channels.js:9
joinCall @ Channels.js:502
executeAction @ mobx.esm.js:1131
joinCall @ mobx.esm.js:1115
connect @ VoiceState.ts:95
executeAction$1 @ mobx.esm.js:1255
ObservableObject.key @ mobx.esm.js:1239
onClick @ HeaderActions.tsx:184
await in onClick (async)
I$4 @ preact.module.js:1
VoiceState.ts:115 Error: Request failed with status code 400
    at createError$1 (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.Ar (xhr.js:66:7)
connect @ VoiceState.ts:115
await in connect (async)
executeAction$1 @ mobx.esm.js:1255
ObservableObject.key @ mobx.esm.js:1239
onClick @ HeaderActions.tsx:184
await in onClick (async)
I$4 @ preact.module.js:1
xhr.js:210          POST https://app.revolt.chat/api/channels/01HK36HXV96X9YEH0AWN5PZSMZ/join_call 400
(anonymous) @ xhr.js:210
xhr @ xhr.js:15
dispatchRequest$1 @ dispatchRequest.js:58
Axios$2.request @ Axios.js:108
(anonymous) @ bind.js:9
req @ index.js:113
post @ index.js:138
(anonymous) @ Channels.js:503
(anonymous) @ Channels.js:13
__awaiter$b @ Channels.js:9
joinCall @ Channels.js:502
executeAction @ mobx.esm.js:1131
joinCall @ mobx.esm.js:1115
connect @ VoiceState.ts:95
executeAction$1 @ mobx.esm.js:1255
ObservableObject.key @ mobx.esm.js:1239
onClick @ HeaderActions.tsx:184
await in onClick (async)
I$4 @ preact.module.js:1
VoiceState.ts:115 Error: Request failed with status code 400
    at createError$1 (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.Ar (xhr.js:66:7)
connect @ VoiceState.ts:115
await in connect (async)
executeAction$1 @ mobx.esm.js:1255
ObservableObject.key @ mobx.esm.js:1239
onClick @ HeaderActions.tsx:184
await in onClick (async)
I$4 @ preact.module.js:1
Session.tsx:171 [FSM 01GVMD5FN32570S5M5NJXC1YKS] {action: 'DISCONNECT'}
Session.tsx:171 [FSM 01GVMD5FN32570S5M5NJXC1YKS] {action: 'RETRY'}
Session.tsx:171 [FSM 01GVMD5FN32570S5M5NJXC1YKS] {action: 'SUCCESS'}
xhr.js:210          POST https://app.revolt.chat/api/channels/01HK36HXV96X9YEH0AWN5PZSMZ/join_call 400
(anonymous) @ xhr.js:210
xhr @ xhr.js:15
dispatchRequest$1 @ dispatchRequest.js:58
Axios$2.request @ Axios.js:108
(anonymous) @ bind.js:9
req @ index.js:113
post @ index.js:138
(anonymous) @ Channels.js:503
(anonymous) @ Channels.js:13
__awaiter$b @ Channels.js:9
joinCall @ Channels.js:502
executeAction @ mobx.esm.js:1131
joinCall @ mobx.esm.js:1115
connect @ VoiceState.ts:95
executeAction$1 @ mobx.esm.js:1255
ObservableObject.key @ mobx.esm.js:1239
onClick @ HeaderActions.tsx:184
await in onClick (async)
I$4 @ preact.module.js:1
VoiceState.ts:115 Error: Request failed with status code 400
    at createError$1 (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.Ar (xhr.js:66:7)
connect @ VoiceState.ts:115
await in connect (async)
executeAction$1 @ mobx.esm.js:1255
ObservableObject.key @ mobx.esm.js:1239
onClick @ HeaderActions.tsx:184
await in onClick (async)
I$4 @ preact.module.js:1
```

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by amycatgirl** [comment]
Not an issue with the client; Vortex is currently down.

The issue is currently being resolved by Insert. Please wait and check back later.

See https://status.revolt.chat to check which services are down.
