### ISSUE TITLE
bug: Bad Request Error for Voice calls in conversations

### ISSUE THREAD

**Issue by NilsEvers** [revoltchat/revite#974]
### What happened?

When trying to start a voice call inside a conversation, by clicking on the phone icon, nothing happens.
The request to `https://app.revolt.chat/api/channels/[CHANNEL-ID]/join_call` fails with status code 400 - Bad Request.

### Branch

Production (app.revolt.chat)

### Commit hash

0f0808a

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 400 ()

Error: Request failed with status code 400
   at createError$1 (createError.js:16:15)
   at settle (settle.js:17:12)
   at XMLHttpRequest.Ar (xhr.js:66:7)
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by kapralnsk** [comment]
Just had the same issue on self-hosted setup and found a discussion for it (w/out a fix tho :( ) https://github.com/orgs/revoltchat/discussions/593

**Comment by MuratDev41** [comment]
Any updates on this? Because i need to create a server for my friends since discord has been banned in turkey

**Comment by KaKi87** [comment]
Hi,

Here's your answer : https://github.com/revoltchat/self-hosted/issues/29#issuecomment-1009377556
